# Generated by Django 4.0.5 on 2022-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
    ]
