# Generated by Django 4.0.5 on 2022-06-26 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0003_currencyuser_currency_alter_currencyuser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReplenishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Сумма пополнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_transaction', to='currency.currency', verbose_name='Вид пополняемой валюты')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replenishment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_buyer', models.FloatField(blank=True, default=None, null=True, verbose_name='Количество валюты которое потратил покупатель')),
                ('value_seller', models.FloatField(blank=True, default=None, null=True, verbose_name='Количество валюты которое продал продавец')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
                ('currency_buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyed_transactions', to='currency.currency', verbose_name='Тип валюты покупателя')),
                ('currency_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selled_transactions', to='currency.currency', verbose_name='Тип валюты продавца')),
                ('seller', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selled_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель')),
            ],
        ),
    ]
