# Generated by Django 4.0.5 on 2022-06-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Имя валюты'),
        ),
    ]
