# Generated by Django 4.0.5 on 2022-06-26 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currency', '0002_alter_currency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyuser',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_users', to='currency.currency', verbose_name='Вид валюты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencyuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currencies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
