# Generated by Django 4.0.5 on 2022-06-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='value',
        ),
        migrations.AddField(
            model_name='lot',
            name='price',
            field=models.FloatField(default=1, verbose_name='Цена лота'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lot',
            name='selled_value',
            field=models.FloatField(default=1, verbose_name='Количество выставленной валюты'),
            preserve_default=False,
        ),
    ]
